In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv(r"C:\Users\iamda\OneDrive\Desktop\Private-MLOPS\MLOPS-Project\notebook\cancer_dataset.csv")

In [6]:
df.head()

Patient_ID  Age  Gender Nationality        Emirate Diagnosis_Date  \
0  PAT000001   69  Female     Emirati  Umm Al Quwain     2020-11-30   
1  PAT000002   32    Male     Emirati  Umm Al Quwain     2015-10-10   
2  PAT000003   89    Male     Emirati      Abu Dhabi     2018-02-13   
3  PAT000004   78  Female     Emirati      Abu Dhabi     2022-02-04   
4  PAT000005   38  Female     Emirati       Fujairah     2019-12-03   

  Cancer_Type Cancer_Stage Treatment_Type Treatment_Start_Date  \
0       Liver           II      Radiation           2020-12-04   
1    Leukemia          III        Surgery           2015-11-05   
2       Liver          III      Radiation           2018-08-03   
3        Lung          III      Radiation           2022-03-13   
4  Pancreatic           II   Chemotherapy           2020-02-29   

                     Hospital Primary_Physician          Outcome Death_Date  \
0     Sheikh Khalifa Hospital          Dr. VO41        Recovered        NaN   
1              Dubai Hospital          Dr. SM31        Recovered        NaN   
2     Zayed Military Hospital           Dr. BC7  Under Treatment        NaN   
3  Cleveland Clinic Abu Dhabi          Dr. TC14        Recovered        NaN   
4     Sheikh Khalifa Hospital          Dr. YS37        Recovered        NaN   

  Cause_of_Death Smoking_Status Comorbidities    Ethnicity  Weight  Height  
0            NaN     Non-Smoker           NaN     European      61     157  
1            NaN         Smoker           NaN  South Asian      80     175  
2            NaN     Non-Smoker           NaN  South Asian      50     175  
3            NaN  Former Smoker           NaN      African      44     155  
4            NaN  Former Smoker           NaN   East Asian     101     160

In [7]:

df.isnull().sum()

Patient_ID                 0
Age                        0
Gender                     0
Nationality                0
Emirate                    0
Diagnosis_Date             0
Cancer_Type                0
Cancer_Stage               0
Treatment_Type             0
Treatment_Start_Date       0
Hospital                   0
Primary_Physician          0
Outcome                    0
Death_Date              9008
Cause_of_Death          9008
Smoking_Status             0
Comorbidities           4047
Ethnicity                  0
Weight                     0
Height                     0
dtype: int64

In [8]:
df.shape

(10000, 20)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   Patient_ID            10000 non-null  object
 1   Age                   10000 non-null  int64 
 2   Gender                10000 non-null  object
 3   Nationality           10000 non-null  object
 4   Emirate               10000 non-null  object
 5   Diagnosis_Date        10000 non-null  object
 6   Cancer_Type           10000 non-null  object
 7   Cancer_Stage          10000 non-null  object
 8   Treatment_Type        10000 non-null  object
 9   Treatment_Start_Date  10000 non-null  object
 10  Hospital              10000 non-null  object
 11  Primary_Physician     10000 non-null  object
 12  Outcome               10000 non-null  object
 13  Death_Date            992 non-null    object
 14  Cause_of_Death        992 non-null    object
 15  Smoking_Status        10000 non-null 

In [10]:

df.head(2)

Patient_ID  Age  Gender Nationality        Emirate Diagnosis_Date  \
0  PAT000001   69  Female     Emirati  Umm Al Quwain     2020-11-30   
1  PAT000002   32    Male     Emirati  Umm Al Quwain     2015-10-10   

  Cancer_Type Cancer_Stage Treatment_Type Treatment_Start_Date  \
0       Liver           II      Radiation           2020-12-04   
1    Leukemia          III        Surgery           2015-11-05   

                  Hospital Primary_Physician    Outcome Death_Date  \
0  Sheikh Khalifa Hospital          Dr. VO41  Recovered        NaN   
1           Dubai Hospital          Dr. SM31  Recovered        NaN   

  Cause_of_Death Smoking_Status Comorbidities    Ethnicity  Weight  Height  
0            NaN     Non-Smoker           NaN     European      61     157  
1            NaN         Smoker           NaN  South Asian      80     175

In [13]:
df2 = df[['Age','Gender','Nationality','Emirate','Cancer_Type','Cancer_Stage','Treatment_Type','Hospital','Primary_Physician','Outcome','Smoking_Status','Ethnicity','Weight','Height']]

In [ ]:

df2.head(2)

Age  Gender Nationality        Emirate Cancer_Type Cancer_Stage  \
0   69  Female     Emirati  Umm Al Quwain       Liver           II   
1   32    Male     Emirati  Umm Al Quwain    Leukemia          III   

  Treatment_Type                 Hospital Primary_Physician    Outcome  \
0      Radiation  Sheikh Khalifa Hospital          Dr. VO41  Recovered   
1        Surgery           Dubai Hospital          Dr. SM31  Recovered   

  Smoking_Status    Ethnicity  Weight  Height  
0     Non-Smoker     European      61     157  
1         Smoker  South Asian      80     175

In [15]:

df2['Age'].unique()

array([69, 32, 89, 78, 38, 41, 20, 39, 70, 19, 47, 55, 81, 77, 50, 75, 66,
       76, 59, 79, 64, 68, 72, 24, 56, 35, 21, 31, 26, 88, 61, 25, 52, 53,
       67, 23, 71, 80, 51, 65, 57, 43, 58, 46, 62, 82, 18, 28, 22, 45, 29,
       40, 54, 44, 60, 30, 49, 83, 74, 87, 73, 36, 85, 34, 86, 33, 37, 84,
       48, 42, 63, 27])

In [16]:
df2['Age'].value_counts()

Age
34    175
43    163
36    159
71    159
38    157
     ... 
31    122
67    120
24    117
51    116
22    113
Name: count, Length: 72, dtype: int64

In [ ]:
df2['Nationality'].unique()

array(['Emirati', 'Expatriate'], dtype=object)

In [18]:
df2['Nationality'].value_counts()

Nationality
Emirati       5920
Expatriate    4080
Name: count, dtype: int64

In [20]:

df2['Emirate'].unique()

array(['Umm Al Quwain', 'Abu Dhabi', 'Fujairah', 'Ras Al Khaimah',
       'Sharjah', 'Dubai', 'Ajman'], dtype=object)

In [21]:
df2['Emirate'].value_counts()

Emirate
Ajman             1497
Fujairah          1471
Abu Dhabi         1471
Umm Al Quwain     1432
Dubai             1407
Sharjah           1382
Ras Al Khaimah    1340
Name: count, dtype: int64

In [22]:

df2['Cancer_Type'].unique()

array(['Liver', 'Leukemia', 'Lung', 'Pancreatic', 'Breast', 'Ovarian',
       'Prostate', 'Colorectal'], dtype=object)

In [23]:
df2['Cancer_Type'].value_counts()

Cancer_Type
Leukemia      1314
Liver         1263
Ovarian       1259
Pancreatic    1243
Breast        1241
Lung          1233
Colorectal    1226
Prostate      1221
Name: count, dtype: int64

In [24]:
df2['Cancer_Stage'].unique()

array(['II', 'III', 'I', 'IV'], dtype=object)

In [25]:

df2['Cancer_Stage'].value_counts()

Cancer_Stage
III    3041
II     3036
I      2419
IV     1504
Name: count, dtype: int64

In [26]:
df2['Treatment_Type'].unique()

array(['Radiation', 'Surgery', 'Chemotherapy', 'Immunotherapy'],
      dtype=object)

In [27]:
df2['Treatment_Type'].value_counts()

Treatment_Type
Radiation        2519
Surgery          2498
Immunotherapy    2497
Chemotherapy     2486
Name: count, dtype: int64

In [28]:
df2['Hospital'].unique()

array(['Sheikh Khalifa Hospital', 'Dubai Hospital',
       'Zayed Military Hospital', 'Cleveland Clinic Abu Dhabi'],
      dtype=object)

In [29]:

df2['Hospital'].value_counts()

Hospital
Sheikh Khalifa Hospital       2541
Cleveland Clinic Abu Dhabi    2535
Dubai Hospital                2467
Zayed Military Hospital       2457
Name: count, dtype: int64

In [30]:

df2['Primary_Physician'].unique()

array(['Dr. VO41', 'Dr. SM31', 'Dr. BC7', ..., 'Dr. WT6', 'Dr. JB17',
       'Dr. SI45'], shape=(8614,), dtype=object)

In [33]:

df2['Primary_Physician'].value_counts()

Primary_Physician
Dr. ZA47    5
Dr. AJ25    5
Dr. IV10    4
Dr. AF32    4
Dr. NO50    4
           ..
Dr. FQ6     1
Dr. YB13    1
Dr. BU36    1
Dr. AP50    1
Dr. NJ38    1
Name: count, Length: 8614, dtype: int64

In [34]:
df2['Outcome'].unique()

array(['Recovered', 'Under Treatment', 'Deceased'], dtype=object)

In [35]:
df2['Outcome'].value_counts()

Outcome
Recovered          4931
Under Treatment    4077
Deceased            992
Name: count, dtype: int64

In [36]:
df2['Smoking_Status'].unique()

array(['Non-Smoker', 'Smoker', 'Former Smoker'], dtype=object)

In [37]:
df2['Smoking_Status'].value_counts()

Smoking_Status
Non-Smoker       5038
Smoker           3045
Former Smoker    1917
Name: count, dtype: int64

In [38]:
df2['Ethnicity'].unique()

array(['European', 'South Asian', 'African', 'East Asian', 'Arab'],
      dtype=object)

In [39]:

df2['Ethnicity'].value_counts()

Ethnicity
South Asian    2083
African        1988
European       1983
Arab           1983
East Asian     1963
Name: count, dtype: int64

In [41]:
df2['Height'].unique()

array([157, 175, 155, 160, 176, 189, 162, 180, 173, 166, 168, 171, 174,
       169, 178, 179, 156, 172, 159, 177, 161, 188, 167, 165, 170, 164,
       191, 192, 181, 187, 144, 183, 149, 163, 182, 184, 185, 138, 152,
       195, 158, 199, 194, 186, 198, 193, 151, 148, 150, 154, 146, 143,
       142, 153, 147, 190, 145, 202, 196, 141, 197, 132, 139, 208, 201,
       200, 136, 137, 204, 140, 206, 131])

In [40]:
df2['Weight'].unique()

array([ 61,  80,  50,  44, 101,  59,  66,  27,  60,  73,  48,  71,  67,
        84,  83,  88,  82,  56,  75,  64,  85,  72,  45,  77,  55,  76,
        89,  49,  99,  81,  78,  94,  95,  87,  53,  70,  41,  39,  57,
        51,  97,  65,  63,  96,  74,  68,  36,  58,  38,  62,  79,  47,
        69,  52,  92,  86,  54, 100,  42,  91, 103,  90,  43,  34,  98,
        18,  40,  93,  37,  35, 117, 109,  46, 107, 106,  32, 102,  24,
        31,  33, 104, 105, 112,  28, 110,  29,  23, 118, 108,  30,  26,
       111, 114,  25, 122, 113, 116, 120,  19,  21,  22, 115])

In [42]:
df2.isnull().sum()

Age                  0
Gender               0
Nationality          0
Emirate              0
Cancer_Type          0
Cancer_Stage         0
Treatment_Type       0
Hospital             0
Primary_Physician    0
Outcome              0
Smoking_Status       0
Ethnicity            0
Weight               0
Height               0
dtype: int64